### ISSUE TITLE
Readme & tags

### ISSUE THREAD

**Issue by Dareka826** [ys-j/YoutubeLiveChatFlusher#1]
I found this repository recently and I think this is a great tool for watching youtube livestreams. However, I really think a readme should be added with information about what this extension does and tags like: "youtube", "niconico", "danmaku", etc. It would really help with discoverability as currently the best way to find this repo is through the mozilla addon store (I think more people would find this through github). As the name of this extension doesn't really convey that it's used for bullet chatting, I think this should be added.

**Comment by ys-j** [comment]
Thank you for your advice.  I added readme, and rephrased statements on [AMO](https://addons.mozilla.org/firefox/addon/youtube-livechat-flusher/).  I hardly understand English, sorry if there are any mistakes.  I'd be glad if you could point out my mistakes or pull requests. Thank you:)
