### ISSUE TITLE
「NGワード設定」の挙動について / Question about the behavior of “NG word settings”

### ISSUE THREAD

**Issue by AzukiSan-png** [ys-j/YoutubeLiveChatFlusher#11]
ver.0.6.3を Google Chrome にて使用して確認しています。
「NGワード設定」の挙動について正しく動作していないように見受けられる挙動や違いのわからない項目がありますので質問させてください。

■確認事項1
モード「メッセージ全体を非表示にする」が動作していないように見受けられます。
「キーワードを非表示にする/置換する」および「文字を伏せ字にする」に設定した場合は、
（置換文字欄を空欄にしていた場合）ちゃんと該当文字が空白になりますが
その動作を確認した状態から「メッセージ全体を非表示にする」に変更しても
メッセージが非表示にされることなく、メッセージ全体が表示されてしまいます。

■確認事項2
「キーワードを非表示にする/置換する」と「文字を伏せ字にする」に違いがないように思えます。
どちらも「置換文字」欄が空欄の場合には該当文字が空白となり、
「置換文字」欄になんらかの文字列を入力していた場合には該当文字が置換文字で置き換えられます。

※上記それぞれの確認時は設定変更や文字入力後に設定画面を [x] クリックで閉じ、ページをリロードしています。

お手数ですがご確認、ご回答をお願いいたします。

**Comment by ys-j** [comment]
@AzukiSan-png さま
ご報告ありがとうございます。
### 確認事項1について
ご指摘の通り実装に誤りがあり、メッセージが非表示にされない不具合を確認しました。次期バージョンにて修正いたしますので、もうしばらくお待ちください。
### 確認事項2ついて
例えばNGワード「こんにちは」に対して「こんにちは～」というメッセージが流れる場合、下記のような動作を意図しています。
| モード＼置換文字 | 空欄 | 〓 |
| :-- | :-- | :-- |
| キーワードを非表示にする/置換する | 〜 | 〓～ |
| 文字を伏せ字にする | 〜 | 〓〓〓〓〓～ |

**Comment by AzukiSan-png** [comment]
確認事項1、および2について承知しました。
不具合修正についてはお時間ができましたらご対応いただければと思います。

**Comment by ys-j** [comment]
@AzukiSan-png さま
本日、確認事項1の不具合についてバージョン0.7.0で応急対応いたしました。ストア掲載の審査が下り次第自動で更新されますので、それまでお待ちください。
不具合が解消しない場合は、改めてご連絡お願いいたします。

**Comment by AzukiSan-png** [comment]
ver.0.7.0 の Chrome 版にて以下の挙動となっていることを確認しました。

・「メッセージ全体を非表示にする」にした場合には登録した単語が含まれるコメントが流れてこない
・「キーワードを非表示にする/置換する」で置換文字を「※」とした場合には、
　登録した単語が含まれるコメントの該当部分が「※」1文字に置き換わった状態でコメントが流れてくる
・「文字を伏せ字にする」で置換文字を「※」とした場合には、
　登録した単語が含まれるコメントの該当部分が文字数に応じた「※」に置き換わった状態でコメントが流れてくる

不具合であった確認事項1について修正対応がなされていること、挙動についての情報を頂いた確認事項2について教えていただいた通りの挙動であること、それぞれについて確認が取れましたので、本件はチケットをクローズとさせていただきます。

この度はご回答ご対応ありがとうございました。
