### ISSUE TITLE
「チャットを流す」が保存されない件について確認事項、及び要望 / Confirmation items regarding the settings of “チャットを流す(chat flow)”

### ISSUE THREAD

**Issue by AzukiSan-png** [ys-j/YoutubeLiveChatFlusher#12]
ver.0.7.0を Google Chrome にて確認。

YouTubeのウィンドウ右下の「設定」から設定変更できる「チャットを流す」のトグルボタンについて、
トグルボタンのオンオフ状態が保存されず、ブラウザでのリロードや新規にYouTubeの配信ページを開くだけでなく、
現在視聴中の配信枠のサイズ変更（「全画面」/「全画面表示を終了」/「シアターモード」）を実行しただけでも
強制的に「チャットを流す」が有効に変更されてしまいます。

現状動作が仕様の場合、ライブ配信中の動画を巻き戻して視聴する場合においても
サイズ変更を行うたびに最新のコメントがチャットとして流れてしまい、
トグルボタンを操作し直す手間が発生して不便に感じますので、
可能でしたら状態を保存できるよう修正のご検討をお願いいたします。

**Comment by ys-j** [comment]
@AzukiSan-png さま
ご指摘ありがとうございます。v0.7.1にて対応いたしましたのでご確認お願いいたします。

**Comment by AzukiSan-png** [comment]
今回の動作確認のために新規にインストールした Firefox では v0.7.1 にて問題なく「チャットを流す」の状態が保存されることを確認できましたが、以前から継続して使用している Chrome では v0.7.1 であって「チャットを流す」の状態が保存されず、配信枠のサイズ変更を行うと設定が有効な状態に巻き戻ってしまいました。

上記は Chrome の再起動を行って確認いたしましたが、今回の機能を利用するためには何らかの設定を初期化したり、プラグインを一旦消すなどの必要はございますでしょうか？

お手数をおかけしますがご確認ご回答をお願いいたします。

**Comment by ys-j** [comment]
@AzukiSan-png さま
申し訳ありません。Chrome版のソースコードに誤りがあり、エラーで状態が保存されていませんでした。改めてバージョン0.7.1.1を公開いたしますので、再度ご確認お願いいたします。

**Comment by AzukiSan-png** [comment]
ご回答ありがとうございます。
Chrome版 v.0.7.1.1 にて「チャットを流す」の設定が
「全画面」/「全画面表示を終了」/「シアターモード」、
及びページを閉じて別のライブ配信の視聴に移った場合に
問題なく保存されていることを確認しました。

現状動作に問題はありませんので、本件はチケットをクローズとさせていただきます。
この度はご対応いただきありがとうございました。
