### ISSUE TITLE
Custom font & own chat style

### ISSUE THREAD

**Issue by Kenqr** [ys-j/YoutubeLiveChatFlusher#3]
Thanks for this awesome extension.

I have 2 feature requests:
* Customize font family and font weight
* Independent settings for your own chat message (in addition to normal, members, moderator, etc)

**Comment by ys-j** [comment]
@Kenqr  Sorry I didn't respond to your request sooner.  I released a new version v0.4.0, please update and check if it works well.  (Chrome version will take longer to review and will be released later.)

**Comment by Kenqr** [comment]
It works pretty well.
Thank you very much.
