### ISSUE TITLE
The font config is suddenly broken today

### ISSUE THREAD

**Issue by billyswong** [ys-j/YoutubeLiveChatFlusher#4]
The live chat flush now go back to standard size text, and the corresponding font setting dialog disappears in Youtube website. I am stuck with the oversize live chat flush with no way to shut it down aside from disabling the extension.

**Comment by ys-j** [comment]
@billyswong  Thank you for your report and sorry for the inconvenience.  What is your environment - OS, browser, extension version?  Also, it would be helpful if you could upload a screenshot.

**Comment by billyswong** [comment]
Strange. The same Youtube video now run chat flush normally again. Sorry for bothering.
