### ISSUE TITLE
表示されるチャットの種類について

### ISSUE THREAD

**Issue by dev-neko** [ys-j/YoutubeLiveChatFlusher#5]
chrome拡張機能として利用している者です。
YouTubeのチャットには以下の2種類から選択して表示が可能ですが、こちらの拡張機能はどちらのチャットの表示に対応しているのでしょうか。
初期状態で「チャットのリプレイ」が表示されているとありがたいです。
ご回答よろしくお願いいたします。

上位のチャットのリプレイ
一部のメッセージ（不適切な可能性があるものなど）を非表示にします

チャットのリプレイ
すべてのメッセージが表示されます

**Comment by ys-j** [comment]
@dev-neko ご利用ありがとうございます。
本拡張機能は、**現在開いているチャット欄**からメッセージを取得しています。
初期状態で「上位のチャットのリプレイ」「トップチャット」が表示されるのはYouTubeの仕様ですが、拡張機能側から変更できるか調べてみます。

**Comment by dev-neko** [comment]
ご回答ありがとうございます。
初期状態では「上位のチャットのリプレイ」が選択されており、毎回手作業で「チャットのリプレイ」を選択する必要があるため、拡張機能側から変更が可能であれば非常にありがたいです。
ご確認いただけるとのことですので、お手数ですが何卒宜しくお願い致します。

**Comment by ys-j** [comment]
お待たせしております。現状、チャットの切り替え方法は力技（DOM操作で「チャットのリプレイ」を選択する）しか見つけられていません。そのため、本拡張機能への対応は見送らせていただきます。

なお、TampermonkeyやGreasemonkey等ユーザースクリプトを実行する拡張機能をインストールされていれば、下記のコードをコピペしていただけると、毎回手作業で選択する必要はなくなります。お手数かと思いますが、よろしくお願いいたします。
```js
// ==UserScript==
// @name         No Top Chat
// @namespace    https://github.com/ys-j/YoutubeLiveChatFlusher
// @version      0.1
// @description  Always show all chats on YouTube.
// @author       ys-j
// @match        *://www.youtube.com/live_chat?*
// @match        *://www.youtube.com/live_chat_replay?*
// @icon         https://raw.githubusercontent.com/ys-j/YoutubeLiveChatFlusher/master/src/icon.svg
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    document.querySelector('yt-live-chat-header-renderer #menu > a:nth-of-type(2)')?.click();
})();
```

**Comment by dev-neko** [comment]
ご確認いただきありがとうございました。
ユーザースクリプトを実行する拡張機能の件検討させて頂きます。
ライブチャットを弾幕風に流す拡張機能の中でこちらが現時点で最も使いやすいため、これからも開発応援しています。
