### ISSUE TITLE
YouTubeの「デザイン」を「ライトモード」を選択していると設定画面の文字が読みにくい

### ISSUE THREAD

**Issue by arigayas** [ys-j/YoutubeLiveChatFlusher#6]
Firefox で使っています。
背景色が白で文字が白になっているのでかなり読みにくいです。
映像の色によっては設定の文字が全く読めない場合があります。
![image](https://github.com/ys-j/YoutubeLiveChatFlusher/assets/11251874/b9c86dda-9d45-4f73-a398-0d0bac4c1e18)

YouTubeの「デザイン」を「ダークモード」と同じ背景色に固定すると良いかもしれません。

**Comment by ys-j** [comment]
@arigayas さま
コメントありがとうございます。バージョン0.5.0.1で修正しました。引き続きよろしくお願いいたします。

**Comment by arigayas** [comment]
修正していただきありがとうございます。

Firefox の Developer Edition と ESR（102.12.0esr） を使っています。
Developer Editionでは更新されて修正されたのを確認したのですが、
ESRでは「新しいFirefox を使ってください」と配布ページで表示されてアップデート出来ませんでした。
ESRに対応していただくことは可能でしょうか？

**Comment by ys-j** [comment]
@arigayas さま
v0.4.2.4以降より拡張機能のマニフェスト仕様をMV2（Manifest V2）からMV3（Manifest V3）に変更したため、Firefox 109以降が必要になります。
Firefox 108以前のバージョンを使用される場合はお手数ですが、[バージョン履歴](https://addons.mozilla.org/ja/firefox/addon/youtube-livechat-flusher/versions/)よりv0.4.2.3をダウンロード・ご利用ください。

**Comment by arigayas** [comment]
@ys-j さま
了解しました。通常版のFirefox かFirefox Developer Editionでこの使用することにします。
