### ISSUE TITLE
It no longer works 

### ISSUE THREAD

**Issue by fireattack** [ys-j/YoutubeLiveChatFlusher#7]
Today I noticed that this extension stops working. 
No danmaku is showing at all in any livestream.

Tried with Firefox and Chrome, using the version in addon/extension store.

**Comment by ys-j** [comment]
@fireattack I'm sorry for the inconvenience.
I couldn't confirm the problem with Firefox and Edge.

Can you reinstall this add-on and teach me for the details? (OS, browser version, region and language)

**Comment by fireattack** [comment]
It started to work again on Chrome.

But I still can't get it work on Firefox.

OS: Win10x64
Brower: Firefox 126.0.1 (64-bit)
Language: English

I tested with a brand new profile with no other addon

The danmaku and the options just don't show up:

![image](https://github.com/ys-j/YoutubeLiveChatFlusher/assets/4130991/7c4160c3-13d5-44d4-81b1-6e6efd3aaeb9)

**Comment by bopeng-hkpc** [comment]
![image](https://github.com/ys-j/YoutubeLiveChatFlusher/assets/162398333/bc1de6ec-17b0-41b5-88e1-9b134ed19ff7)

It stops working again today. 

Using Firefox 128.0a1 (2024-06-08) (64-bit) and newest Chrome.
Windows 10 x64, language = Englsih

**Comment by fireattack** [comment]
It stops working again today.

Chrome: 125.0.6422.144 (Official Build) (64-bit) (cohort: Control) 

Firefox: 129.0a1 20240612215151

All tested with new profile, no other addons.
OS: Windows 10, English.

![image](https://github.com/ys-j/YoutubeLiveChatFlusher/assets/4130991/2b256d06-005e-4f72-b649-c80aa65b3252)

**Comment by ys-j** [comment]
@fireattack I'm sorry to keep bothering you.
I'd found that the add-on doesn't work with URL beginning with "www.youtube.com/live/".
Just fixed, please wait for a new version v0.5.3 to be released.
