### ISSUE TITLE
What is the meaning of each options under Simultaneous Msg setting?

### ISSUE THREAD

**Issue by LifeJustDLC** [ys-j/YoutubeLiveChatFlusher#9]
wikiではこう書かれたけど：

![图片](https://github.com/ys-j/YoutubeLiveChatFlusher/assets/112793544/38af380d-500d-4941-8af2-7cfbe8f78549)

以下4つのオプションの詳細はいまいち分からない：

![图片](https://github.com/ys-j/YoutubeLiveChatFlusher/assets/112793544/14b3cb62-96e6-4e00-babc-1efbf250c27a)

**Comment by ys-j** [comment]
チャットが多い動画で有効な設定項目です。
It is an effective setting for videos with a lot of chatting.

例 / Example: https://www.youtube.com/watch?v=tuWw5EQPGlc

例えば、同時に下記のコメントを読み込んだときの挙動は下表の通りになります。 
For example, if the following chat messages are loaded at the same time, the behavior will be as shown in the table below.

| Timestamp | Loaded messages |
| --- | --- |
| 4:45.000 | `B` `B` `A` |
| 4.45.500 | `A` `B` `C` `A` `B` `A` `A` `B` `A` |

| Option | Behavior |
| --- | --- |
| 全て流す<br>Flush all messages | 全てのメッセージが流れる<br>All messages will be displayed.<br>4:45.000: `B` `B` `A`<br>4:45.500: `A` `B` `C` `A` `B` `A` `A` `B` `A` |
|読み込む毎に最初のチャットのみ流す<br> Flush only first message per load | 最初のメッセージが流れる<br>First message will be displayed.<br>4:45.000: `B`<br>4:45.500: `A` |
| 同じ内容を統合する<br>Merge same messages | ユニークなメッセージのみ流れる<br>Unique messages loaded at the same time will be displayed.<br>4:45.000: `B` `A`<br>4:45.500: `A` `B` `C` |
| 直前を含めて同じ内容を統合する<br>Merge same messages including last one | 直前の読み込みを含めユニークなメッセージのみ流れる<br>Unique messages loaded at the same or last time will be displayed.<br>4:45.000: `B` `A`<br>4:45.500: `B` `C` |

**Comment by LifeJustDLC** [comment]
@ys-j Thanks for your explanation.
